wireguard:
    wg0: ENC[AES256_GCM,data:VQ+zwFIXV8fLt/akdcCP3474LBCgHA==,iv:Mp+4OMsmS9HCn+zWn8271Huqr1RPTX8BdXa1GCBeZpo=,tag:SpR5cPL/TL0WTaNEljSC9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g0h7h6ca8egk7un45zcfewumcpjmehc33uh2r529phrlerp67vkqcckjq2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb2lwRGhJaWhVZXVESmwv
            eUJKWWwzaEV3NXZycERUMkxod1F2NXZGaUNNCmdDYzBpbEVrdDdvWHBQakhQVit2
            TURMNnd1dSs2V0tvZXRFQ0djL0FBMzAKLS0tIFR0RVVRTStLRlk0anJHQmFkaW91
            QXgxaWF2Wm5uWjdIRldjUHNwdE5IUTgKQhuYf97NkOhpvdw/Dw0H7DkNtSjTEz5S
            KcRxUID/N4ShtY5f5SvMB9b28qQiPl0ptYkhKNyaXYqG3yCqqXtnDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T14:53:04Z"
    mac: ENC[AES256_GCM,data:Ug1zd5BFM7HSrogSvfa1lFJrF5JS0rEpLkC1dqQrLU50OhYOlergS3xhW+CyN4H3WViJ3cuOD6O2iDay6NWGMfoXkazDZI2ECJDOQITRYjHu1n/FVDHW3lcaMP5SSjMfAbopFl8CHI/iYFkeF+m3bq2bnp9ghief7WCnIIhMXzc=,iv:/o8S6fXYqBPWLNrbm9+126SSs6isNa7TZKYD5EYhGko=,tag:tANRyVqslbK1SV4PUYC4oA==,type:str]
    pgp:
        - created_at: "2023-04-28T14:52:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DR4BMmtywY4USAQdAjhWWwltmHj3dsQjDwsXxDVLv67cbLg20vimuvDkzzQQw
            nBtniV/mBbZeToBuzWF8jOAzGHXoO8xKtSy09PK5p09sFoTE4aJNc0Ic19RsQZwg
            1GgBCQIQ5j7TkitcC6lOP3Cj+3aVpyMWzSeA359YNhQ5xB51wyHCcE7o6vnSzepr
            Wc0NFDdcrHaW9u9/cwpCpq/r0+xcw+D0WGnenDX4CYk54whXrDbuSlHD+BtAuCGV
            +PFGXN18Ns+2gw==
            =iWp4
            -----END PGP MESSAGE-----
          fp: A65CB8AFC2FA898C7AFB01D33A054427831129CB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
