# Nixobolus - Automated creation of bootable NixOS images
# https://github.com/ponkila/Nixobolus

hosts:
  - name: "fungus"
    user: "core"
    shell: "bash"
    timezone: "Europe/Helsinki"
    keymap: "fi"

    home_manager:
      enable: true
      version: "23.05"
      programs: [ vim, git ]

    services:
      ssh:
        enable: true
        permit_root_login: false
        password_auth: false
        public_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKEdpdbTOz0h9tVvkn13k1e8X7MnctH3zHRFmYWTbz9T kari@torque