# Nixobolus - Automated creation of bootable NixOS images
# https://github.com/ponkila/Nixobolus

# Store commonly used values to be referenced later.
variables:
    var_1: &addr 192.168.100.10

# General settings that apply to all machines.
general:
    user: core
    shell: fish
    timezone: Europe/Helsinki
    keymap: fi
    home_manager:
        version: "23.05"
        nix_packages:
            - file
            - tree
            - bind
        programs:
            - tmux
            - htop
            - vim
            - git
    services:
        ssh:
            enable: true
            permit_root_login: false
            password_auth: false
            public_keys:
                - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNMKgTTpGSvPG4p8pRUWg1kqnP9zPKybTHQ0+Q/noY5+M6uOxkLy7FqUIEFUT9ZS/fflLlC/AlJsFBU212UzobA= ssh@secretive.sandbox.local
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKEdpdbTOz0h9tVvkn13k1e8X7MnctH3zHRFmYWTbz9T kari@torque

# Specific configuration for each individual machine. 
hosts:
    - name: muhos
      mounts:
        - source: /dev/disk/by-label/erigon
          target: /var/mnt/erigon
          desc: Erigon Storage
          options:
            - noatime
        - source: /dev/disk/by-label/lighthouse
          target: /var/mnt/lighthouse
          desc: Lighthouse Storage
          options:
            - noatime
      services:
        wireguard:
            interface: dinar
            address: 192.168.100.10/32
            private_key: ENC[AES256_GCM,data:0fN41KSlOq5GEJe76UrNPyV6rQXMPqjj7VcCuVYWCoh3hi/S/DtKixpIPXA=,iv:QGvW4cYLnyf2WAb3aqTollnxta2aFkgP3KS/M84oqMY=,tag:/jG7lOVMGSQ8xU4sNs7iSA==,type:str]
            peers:
                - public_key: ENC[AES256_GCM,data:yrzVCqh1Gy3/ZJZzIlK7vSieAc85+vWtyEmw1ukDnOeEPBI/0Q2PlkHN3lo=,iv:4QGRMFwqFz3Rk5myGDqLCUzRafyJFebphx0jSMb5j/M=,tag:mTQouou9tsi9hDwD11OE7Q==,type:str]
                  allowed_ips: 192.168.100.0/24
                  endpoint: ENC[AES256_GCM,data:cd4ZCVlLR/sxtFdiBbyaaY1bTg==,iv:/gV5964inWaFhLiXjb7tRFCaOeiDpzsaaSE9S9NDAdw=,tag:spOy8+3PQpSEfok2wJlG7g==,type:str]
                  persistent_keepalive: 25
        ethereum:
            network: mainnet
            clients:
                # Execution
                erigon:
                    enable: true
                    data_dir: /var/mnt/erigon
                    infra_ip: *addr
                    authrpc_hosts:
                        - '*'
                    authrpc_addr: *addr
                    authrpc_jwtsecret: /var/mnt/erigon/jwt.hex
                    metrics_enable: true
                    externalcl_enable: true
                # Consensus
                lighthouse:
                    enable: true
                    data_dir: /var/mnt/lighthouse
                    infra_ip: *addr
                    http_enable: true
                    http_addr: *addr
                    execution_port: 8551
                    execution_endpoint: *addr
                    jwt_secret: /var/mnt/lighthouse/jwt.hex
                    mev_enable: true
                    mev_port: 18550
                    mev_endpoint: *addr
                    slasher_enable: true
                    slasher_history_length: 256
                    slasher_max_db_size: 16
                    prune_payloads_enable: false
                    metrics_enable: true

# Added by SOPS
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-28T22:28:30Z"
    mac: ENC[AES256_GCM,data:7jcn6eF4D4xhCPyp/hZJn1WNmoPCdvCXM/Ia8NAa6U3EIDrx4qTF6eOvdStl6aGu/mK8eclEWPsQLMuiU/uvYyBUZdxPqu1wQCXtKPiDAaXrzybMm5A/aypD1NWh2CPB5fX73xoXSq1y1ugnF25Blr9mQij+IFSI7g5tnlSDKms=,iv:qKYlgV45+spxAS8egyAKtSpGFPxQ/y8rvge4jek51sg=,tag:Ie03OLLf8mopM1hGGJRRMw==,type:str]
    pgp:
        - created_at: "2023-02-28T22:28:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0asU2osiQzOAQv+Ny0rbPJ0sK7j4dQve8ugDUpP+Ky4bntg+c41vwixnx/f
            ZlAaqHPKCb+ZZ9cdWqZGDkxjZdee3qglgEVV+c/gpQAPJ6FtrwO44HHRj1JY1nWl
            sOiVUTHuvL/t0kLkLVBMb5zgE+zaAPt8E+2fqzy3Lvmx7tcrDD9b+JDWF4Tj3dFY
            RHFmFXm6o4qlcSUPtgZLzVHtQtkEMfNzs+Nws4YtQYYSd62sj925t5j6Ok1QUCV0
            /YMu3N8bXmWe91d6/lF6sLQuhozgmVsbkt7nr4taR+kBLHyglFBRVLXIfstUieJ/
            vpRCiyoQG3x0J5/ku5lu1+i0tbP8jhT7KpR0f3GCn3IGzg+GjYoRjXQVzhYJM7aL
            jrzcF+dO95JoRmgAt+ETF+ajii/z8HqEO8+kh/GQQhhSB7TGwV7DWZq9ppQGiHxL
            NmnegLl5KaChLYWRzn3xz0tm9vqltsAuQ1Wd4hOUPkPzxp5ErFAeppANM36a5it2
            pSdulE9VVcgSohQIh8IT0l4BNMLgESh8UzwXljwsgRaH8bsuUHmRmNUeKaRp0PjY
            bcuJVV8/KVRSyKNBleVGe3AzIDtpL8F5huIWCXH65CXt13DXXz8Pr0QX1MUaKFUy
            8cHpHvyW5vgK0fiTIucV
            =Y50s
            -----END PGP MESSAGE-----
          fp: 89514318CC412AB3DA074269BF90825A41685E00
    encrypted_regex: ^(public_key|private_key|endpoint)$
    version: 3.7.3
